export enum Role {
    ADMIN = 'admin',
    LAW_ENFORCEMENT = "law enforcement",
    CITIZEN = "citizen"
}

export enum PermissionFlag { 
    FREE_PERMISSION = 1,
    PAID_PERMISSION = 2,
    ANOTHER_PAID_PERMISSION = 4,
    ADMIN_PERMISSION = 8,
    ADMIN_PERMISSION_NOT_ALL_PERMISSIONS = 7,
    LAW_ENFORCEMENT_ADMIN_PERMISSION = 5,
    LAW_ENFORCEMENT_PERMISSIONS = 3,
    ALL_PERMISSIONS = 2147483647,
}