export enum PermissionFlag {
    FREE_PERMISSION = 1,
    PAID_PERMISSION = 2,
    ANOTHER_PAID_PERMISSION = 4,
    ADMIN_PERMISSION = 8,
    ADMIN_PERMISSION_NOT_ALL_PERMISSIONS = 7,
    ALL_PERMISSIONS = 2147483647,
}
